// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package hcpv1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using HCCLink within kubernetes types, where deepcopy-gen is used.
func (in *HCCLink) DeepCopyInto(out *HCCLink) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCCLink. Required by controller-gen.
func (in *HCCLink) DeepCopy() *HCCLink {
	if in == nil {
		return nil
	}
	out := new(HCCLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new HCCLink. Required by controller-gen.
func (in *HCCLink) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
