# Note this arg has to be before the first FROM
ARG ENVOY_VERSION

FROM consul-dev as consul

FROM docker.mirror.hashicorp.services/envoyproxy/envoy:v${ENVOY_VERSION}
COPY --from=consul /bin/consul /bin/consul
