FROM docker.mirror.hashicorp.services/fortio/fortio AS fortio

FROM docker.mirror.hashicorp.services/docker/bats/bats:latest

RUN apk add curl
RUN apk add openssl
RUN apk add jq
COPY --from=fortio /usr/bin/fortio /usr/sbin/fortio
