FROM docker.mirror.hashicorp.services/windows/fortio AS fortio

FROM docker.mirror.hashicorp.services/windows/bats:1.7.0

RUN choco install openssl -yf
RUN choco install jq -yf

COPY --from=fortio C:\\fortio C:\\fortio

ENV PATH C:\\fortio;%PATH%
ENV PATH C:\\Windows\\System32;%PATH%
ENV PATH C:\\ProgramData\\chocolatey\\lib\\jq\\tools;%PATH%
