.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "COREDNS\-READY" "7" "March 2019" "CoreDNS" "CoreDNS plugins"
.
.SH "NAME"
\fIready\fR \- enables a readiness check HTTP endpoint\.
.
.SH "DESCRIPTION"
By enabling \fIready\fR an HTTP endpoint on port 8181 will return 200 OK, when all plugins that are able to signal readiness have done so\. If some are not ready yet the endpoint will return a 503 with the body containing the list of plugins that are not ready\. Once a plugin has signaled it is ready it will not be queried again\.
.
.P
Each Server Block that enables the \fIready\fR plugin will have the plugins \fIin that server block\fR report readiness into the /ready endpoint that runs on the same port\.
.
.SH "SYNTAX"
.
.nf

ready [ADDRESS]
.
.fi
.
.P
\fIready\fR optionally takes an address; the default is \fB:8181\fR\. The path is fixed to \fB/ready\fR\. The readiness endpoint returns a 200 response code and the word "OK" when this server is ready\. It returns a 503 otherwise\.
.
.SH "PLUGINS"
Any plugin wanting to signal readiness will need to implement the \fBready\.Readiness\fR interface by implementing a method \fBReady() bool\fR that returns true when the plugin is ready and false otherwise\.
.
.SH "EXAMPLES"
Let \fIready\fR report readiness for both the \fB\.\fR and \fBexample\.org\fR servers (assuming the \fIwhois\fR plugin also exports readiness):
.
.IP "" 4
.
.nf

\&\. {
    ready
    erratic
}

example\.org {
    ready
    whoami
}
.
.fi
.
.IP "" 0
.
.P
Run \fIready\fR on a different port\.
.
.IP "" 4
.
.nf

\&\. {
    ready localhost:8091
}
.
.fi
.
.IP "" 0

