# Note these args have to be before the first FROM
ARG CONSUL_IMAGE
ARG ENVOY_VERSION

FROM ${CONSUL_IMAGE} as consul

FROM docker.mirror.hashicorp.services/envoyproxy/envoy:v${ENVOY_VERSION}

# On Mac M1s when TProxy is enabled, envoy containers spawned from this image
# (only used in consul-container integration tests) may fail to apply nftables rules.
# This is because the nf_tables kernel module is not available under Docker Desktop's
# Linux VM on Apple Silicon. TProxy tests on Mac M1s will fail locally but pass in CI.
#
# Install nftables and sudo, needed for tproxy.
RUN apt update -y \
	&& apt install -y nftables sudo curl dnsutils \
	&& adduser envoy sudo \
	&& echo 'envoy ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY tproxy-startup.sh /bin/tproxy-startup.sh
RUN chmod +x /bin/tproxy-startup.sh \
	&& chown envoy:envoy /bin/tproxy-startup.sh

COPY --from=consul /bin/consul /bin/consul

USER envoy
