# Copyright IBM Corp. 2024, 2026
# SPDX-License-Identifier: BUSL-1.1

ARG CONSUL_DATAPLANE_IMAGE
ARG CONSUL_IMAGE

# Docker doesn't support expansion in COPY --copy, so we need to create an intermediate image.
FROM ${CONSUL_IMAGE} as consul

FROM ${CONSUL_DATAPLANE_IMAGE} as consuldataplane

USER root

# On Mac M1s when TProxy is enabled, consul-dataplane containers spawned from this image
# (only used in consul-container integration tests) may fail to apply nftables rules.
# This is because the nf_tables kernel module is not available under Docker Desktop's
# Linux VM on Apple Silicon. TProxy tests on Mac M1s will fail locally but pass in CI.
RUN microdnf install -y nftables sudo nc \
 	&& usermod -a -G wheel consul-dataplane \
 	&& echo 'consul-dataplane ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY --from=consul /bin/consul /bin/consul

COPY tproxy-startup.sh /bin/tproxy-startup.sh
RUN chmod +x /bin/tproxy-startup.sh && chown root:root /bin/tproxy-startup.sh

USER 100

