version: 2
updates:
- package-ecosystem: gomod
  open-pull-requests-limit: 30
  directory: /
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
- package-ecosystem: npm
  open-pull-requests-limit: 30
  directory: /ui
  schedule:
    interval: daily
- package-ecosystem: npm
  open-pull-requests-limit: 30
  directory: /website
  schedule:
    interval: daily
