# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

pr/dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - vendor/**/*
      - go.*
theme/acls:
  - changed-files:
    - any-glob-to-any-file:
      - acl/**/*
theme/agent-cache:
  - changed-files:
    - any-glob-to-any-file:
      - agent/cache/**/*
theme/api:
  - changed-files:
    - any-glob-to-any-file:
      - api/**/*
theme/catalog:
  - changed-files:
    - any-glob-to-any-file:
      - agent/catalog/**/*
theme/certificates:
  - changed-files:
    - any-glob-to-any-file:
      - tlsutil/**/*
theme/cli:
  - changed-files:
    - any-glob-to-any-file:
      - command/**/*
theme/config:
  - changed-files:
    - any-glob-to-any-file:
      - agent/config/**/*
theme/connect:
  - changed-files:
    - any-glob-to-any-file:
      - connect/**/*
      - agent/connect/**/*
# theme/consul-nomad:
theme/consul-terraform-sync:
  - changed-files:
    - any-glob-to-any-file:
      - website/content/docs/nia/**/*
      - website/content/docs/integrate/nia*
# theme/consul-vault:
theme/contributing:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**/*
theme/dns:
  - changed-files:
    - any-glob-to-any-file:
      - dns/**/*
theme/envoy/xds:
  - changed-files:
    - any-glob-to-any-file:
      - agent/xds/**/*
# theme/federation-usability:
theme/health-checks:
  - changed-files:
    - any-glob-to-any-file:
      - agent/health*
      - api/health*
# theme/ingress-gw:
# theme/internal-cleanup:
theme/internals:
  - changed-files:
    - any-glob-to-any-file:
      - lib/**/*
      - types/**/*
# theme/kubernetes:
# theme/mesh-gw:
# theme/operator-usability:
# theme/performance:
# theme/service-metadata:
# theme/streaming:
theme/telemetry:
  - changed-files:
    - any-glob-to-any-file:
      - logging/**/*
# theme/terminating-gw:
theme/testing:
  - changed-files:
    - any-glob-to-any-file:
      - ./*test*/**/*
theme/tls:
  - changed-files:
    - any-glob-to-any-file:
      - tlsutil/**/*
theme/ui:
  - changed-files:
    - any-glob-to-any-file:
      - ui/**/*
# theme/windows:
# thinking:
# type/bug:
type/ci:
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/*
# type/crash:
type/docs:
  - changed-files:
    - any-glob-to-any-file:
      - website/**/*
