linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - unconvert
    - staticcheck

issues:
  # Disable the default exclude list so that all excludes are explicitly
  # defined in this file.
  exclude-use-default: false

  exclude-rules:
    # Temp Ignore SA9004: only the first constant in this group has an explicit type
    # https://staticcheck.io/docs/checks#SA9004
    - linters: [staticcheck]
      text: "SA9004:"

linters-settings:
  gofmt:
    simplify: false

run:
  timeout: 10m
