# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

dir: grpcmocks/{{.InterfaceDirRelative}}
exclude-interface-regex: (serverStream|Is(Inmem|Cloning).*Client)
include-interface-regex: .*
structname: '{{.InterfaceName}}'
pkgname: mock{{.SrcPackageName}}
recursive: true
template: testify
filename: 'mock_{{.InterfaceName}}.go'
template-data:
  unroll-variadic: true
packages:
  github.com/hashicorp/consul/proto-public/pbacl: {}
  github.com/hashicorp/consul/proto-public/pbconnectca: {}
  github.com/hashicorp/consul/proto-public/pbdataplane: {}
  github.com/hashicorp/consul/proto-public/pbdns: {}
  github.com/hashicorp/consul/proto-public/pbresource: {}
  github.com/hashicorp/consul/proto-public/pbserverdiscovery: {}