# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

with-expecter: true
recursive: true
include-regex: ".*"
exclude-regex: "(serverStream|Is(Inmem|Cloning).*Client)"
# We don't want the mocks within proto-public to prevent forcing a dependency
# of the testify library on the modules usage. The mocks are only for
# internal testing purposes. Other consumers can generated the mocks into
# their own code base.
dir: "grpcmocks/{{.InterfaceDirRelative}}"
outpkg: "mock{{.PackageName}}"
mockname: "{{.InterfaceName}}"
packages:
  github.com/hashicorp/consul/proto-public/pbacl:
  github.com/hashicorp/consul/proto-public/pbconnectca:
  github.com/hashicorp/consul/proto-public/pbdataplane:
  github.com/hashicorp/consul/proto-public/pbserverdiscovery:
  github.com/hashicorp/consul/proto-public/pbresource:
  github.com/hashicorp/consul/proto-public/pbdns:
