with-expecter: true
all: true
recursive: false
dir: "{{.PackageName}}mock"
outpkg: "{{.PackageName}}mock"
mockname: "{{.InterfaceName}}"
packages:
  github.com/hashicorp/consul/internal/controller/dependency:
