// Code generated by protoc-json-shim. DO NOT EDIT.
package catalogv2beta1

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for WorkloadSelector
func (this *WorkloadSelector) MarshalJSON() ([]byte, error) {
	str, err := SelectorMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for WorkloadSelector
func (this *WorkloadSelector) UnmarshalJSON(b []byte) error {
	return SelectorUnmarshaler.Unmarshal(b, this)
}

var (
	SelectorMarshaler   = &protojson.MarshalOptions{}
	SelectorUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
