// Code generated by protoc-json-shim. DO NOT EDIT.
package hcpv2

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for HCPConfig
func (this *HCPConfig) MarshalJSON() ([]byte, error) {
	str, err := HcpConfigMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HCPConfig
func (this *HCPConfig) UnmarshalJSON(b []byte) error {
	return HcpConfigUnmarshaler.Unmarshal(b, this)
}

var (
	HcpConfigMarshaler   = &protojson.MarshalOptions{}
	HcpConfigUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
