# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

with-expecter: true
all: true
recursive: false
dir: "controllermock"
outpkg: "controllermock"
mockname: "{{.InterfaceName}}"
packages:
  github.com/hashicorp/consul/internal/controller:
