FROM mcr.microsoft.com/windows/nanoserver:1809

RUN mkdir fortio

ENV FORTIO_URL=https://github.com/fortio/fortio/releases/download/v1.33.0/fortio_win_1.33.0.zip
RUN curl %FORTIO_URL% -L -o fortio.zip

RUN tar -xf fortio.zip -C fortio

ENV PATH C:\\fortio;%PATH%

EXPOSE 8078/tcp
EXPOSE 8079/tcp
EXPOSE 8080/tcp
EXPOSE 8081/tcp

ENTRYPOINT ["fortio.exe"]
CMD [ "fortio.exe", "server" ]