FROM mcr.microsoft.com/windows/servercore:1809

EXPOSE 5775/udp

EXPOSE 6831/udp

EXPOSE 6832/udp

EXPOSE 5778/tcp

EXPOSE 14268/tcp

EXPOSE 14250/tcp

EXPOSE 16686/tcp

ENV JAEGER_URL=https://github.com/jaegertracing/jaeger/releases/download/v1.11.0/jaeger-1.11.0-windows-amd64.tar.gz
RUN curl %JAEGER_URL% -L -o jaeger.tar.gz

RUN mkdir jaeger
RUN tar -xf jaeger.tar.gz -C jaeger --strip-components=1

RUN cd "C:\\jaeger" && echo {"default_strategy":{"type":"probabilistic","param":1}} > sampling_strategies.json

ENTRYPOINT ["C:\\jaeger\\jaeger-all-in-one.exe"]

CMD ["--sampling.strategies-file=C:\\jaeger\\sampling_strategies.json"]