# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

with-expecter: true
recursive: false
all: true
# We don't want the mocks within proto-public so as to force a dependency
# of the testify library on the modules usage. The mocks are only for
# internal testing purposes. Other consumers can generated the mocks into
# their own code base.
dir: "{{.PackageName}}mock"
outpkg: "{{.PackageName}}mock"
mockname: "{{.InterfaceName}}"
packages:
  github.com/hashicorp/consul/internal/mesh/internal/controllers/routes/xroutemapper:
