// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: BUSL-1.1

// Code generated by update-latest-versions.sh. DO NOT EDIT.

package topology

const (
    DefaultConsulCEImage         = "hashicorp/consul:1.21.2"
    DefaultConsulEnterpriseImage = "hashicorp/consul-enterprise:1.21.2-ent"
    DefaultEnvoyImage            = "envoyproxy/envoy:v1.33.2"
    DefaultDataplaneImage        = "hashicorp/consul-dataplane:1.7.2"
)
