// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package meshv2beta1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using APIGateway within kubernetes types, where deepcopy-gen is used.
func (in *APIGateway) DeepCopyInto(out *APIGateway) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIGateway. Required by controller-gen.
func (in *APIGateway) DeepCopy() *APIGateway {
	if in == nil {
		return nil
	}
	out := new(APIGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new APIGateway. Required by controller-gen.
func (in *APIGateway) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using APIGatewayListener within kubernetes types, where deepcopy-gen is used.
func (in *APIGatewayListener) DeepCopyInto(out *APIGatewayListener) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIGatewayListener. Required by controller-gen.
func (in *APIGatewayListener) DeepCopy() *APIGatewayListener {
	if in == nil {
		return nil
	}
	out := new(APIGatewayListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new APIGatewayListener. Required by controller-gen.
func (in *APIGatewayListener) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using APIGatewayTLSConfiguration within kubernetes types, where deepcopy-gen is used.
func (in *APIGatewayTLSConfiguration) DeepCopyInto(out *APIGatewayTLSConfiguration) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIGatewayTLSConfiguration. Required by controller-gen.
func (in *APIGatewayTLSConfiguration) DeepCopy() *APIGatewayTLSConfiguration {
	if in == nil {
		return nil
	}
	out := new(APIGatewayTLSConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new APIGatewayTLSConfiguration. Required by controller-gen.
func (in *APIGatewayTLSConfiguration) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
