// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package meshv2beta1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using GatewayClassConfig within kubernetes types, where deepcopy-gen is used.
func (in *GatewayClassConfig) DeepCopyInto(out *GatewayClassConfig) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayClassConfig. Required by controller-gen.
func (in *GatewayClassConfig) DeepCopy() *GatewayClassConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayClassConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GatewayClassConfig. Required by controller-gen.
func (in *GatewayClassConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CopyAnnotations within kubernetes types, where deepcopy-gen is used.
func (in *CopyAnnotations) DeepCopyInto(out *CopyAnnotations) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyAnnotations. Required by controller-gen.
func (in *CopyAnnotations) DeepCopy() *CopyAnnotations {
	if in == nil {
		return nil
	}
	out := new(CopyAnnotations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CopyAnnotations. Required by controller-gen.
func (in *CopyAnnotations) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Deployment within kubernetes types, where deepcopy-gen is used.
func (in *Deployment) DeepCopyInto(out *Deployment) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Deployment. Required by controller-gen.
func (in *Deployment) DeepCopy() *Deployment {
	if in == nil {
		return nil
	}
	out := new(Deployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Deployment. Required by controller-gen.
func (in *Deployment) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
