// Code generated by protoc-json-shim. DO NOT EDIT.
package meshv2beta1

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for MeshGateway
func (this *MeshGateway) MarshalJSON() ([]byte, error) {
	str, err := MeshGatewayMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MeshGateway
func (this *MeshGateway) UnmarshalJSON(b []byte) error {
	return MeshGatewayUnmarshaler.Unmarshal(b, this)
}

// MarshalJSON is a custom marshaler for MeshGatewayListener
func (this *MeshGatewayListener) MarshalJSON() ([]byte, error) {
	str, err := MeshGatewayMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MeshGatewayListener
func (this *MeshGatewayListener) UnmarshalJSON(b []byte) error {
	return MeshGatewayUnmarshaler.Unmarshal(b, this)
}

var (
	MeshGatewayMarshaler   = &protojson.MarshalOptions{}
	MeshGatewayUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
