// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package meshv2beta1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using ProxyConfiguration within kubernetes types, where deepcopy-gen is used.
func (in *ProxyConfiguration) DeepCopyInto(out *ProxyConfiguration) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfiguration. Required by controller-gen.
func (in *ProxyConfiguration) DeepCopy() *ProxyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProxyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfiguration. Required by controller-gen.
func (in *ProxyConfiguration) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DynamicConfig within kubernetes types, where deepcopy-gen is used.
func (in *DynamicConfig) DeepCopyInto(out *DynamicConfig) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicConfig. Required by controller-gen.
func (in *DynamicConfig) DeepCopy() *DynamicConfig {
	if in == nil {
		return nil
	}
	out := new(DynamicConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DynamicConfig. Required by controller-gen.
func (in *DynamicConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using TransparentProxy within kubernetes types, where deepcopy-gen is used.
func (in *TransparentProxy) DeepCopyInto(out *TransparentProxy) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentProxy. Required by controller-gen.
func (in *TransparentProxy) DeepCopy() *TransparentProxy {
	if in == nil {
		return nil
	}
	out := new(TransparentProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new TransparentProxy. Required by controller-gen.
func (in *TransparentProxy) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using BootstrapConfig within kubernetes types, where deepcopy-gen is used.
func (in *BootstrapConfig) DeepCopyInto(out *BootstrapConfig) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapConfig. Required by controller-gen.
func (in *BootstrapConfig) DeepCopy() *BootstrapConfig {
	if in == nil {
		return nil
	}
	out := new(BootstrapConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapConfig. Required by controller-gen.
func (in *BootstrapConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AccessLogsConfig within kubernetes types, where deepcopy-gen is used.
func (in *AccessLogsConfig) DeepCopyInto(out *AccessLogsConfig) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessLogsConfig. Required by controller-gen.
func (in *AccessLogsConfig) DeepCopy() *AccessLogsConfig {
	if in == nil {
		return nil
	}
	out := new(AccessLogsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AccessLogsConfig. Required by controller-gen.
func (in *AccessLogsConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using EnvoyExtension within kubernetes types, where deepcopy-gen is used.
func (in *EnvoyExtension) DeepCopyInto(out *EnvoyExtension) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyExtension. Required by controller-gen.
func (in *EnvoyExtension) DeepCopy() *EnvoyExtension {
	if in == nil {
		return nil
	}
	out := new(EnvoyExtension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyExtension. Required by controller-gen.
func (in *EnvoyExtension) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
