FROM docker.mirror.hashicorp.services/windows/openjdk:1809

RUN mkdir zipkin
RUN curl.exe -sSL 'https://search.maven.org/remote_content?g=io.zipkin&a=zipkin-server&v=LATEST&c=exec' -o zipkin/zipkin.jar

EXPOSE 9410/tcp

EXPOSE 9411/tcp

WORKDIR /zipkin

ENTRYPOINT ["java", "-jar", "zipkin.jar"]