{
 "title": "Consul K8s monitoring (control plane)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Consul Servers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "consul_consul_server_0_consul_members_servers{pod=\"consul-server-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Connected Consul-dataplanes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(consul_dataplane_envoy_connected)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Leader (1: Healthy)",
   "type": "timeseries",
   "description": "Must be 1",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum({__name__=~\".+server_isLeader\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consul Server Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(consul_consul_server_0_version{pod=\"consul-server-0\"}) by (version)"
    }
   ]
  },
  {
   "title": "Number of Consul Clients (No data in agentless mode)",
   "type": "stat",
   "description": "No data in agentless mode",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_resource_limits{pod=~\"consul-client-.*\", container=\"consul\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raft Leader LastContact 99th and 50th (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "consul_raft_leader_lastContact{quantile=\"0.5\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "consul_raft_leader_lastContact{quantile=\"0.99\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Follower Append Entries Latency 99th and 50th (ms)",
     "type": "timeseries",
     "description": "Use consul.raft.rpc.appendEntries to understand how long it takes a follower node to process newly received Raft logs from the leader. Like consul.raft.commitTime, increases in this metric can indicate higher load on your Consul servers, and come with a risk of stale data. Since this metric is exposed within each follower, you should aggregate it as both an average (to track overall load on your Raft servers) and a percentile (to watch for outlier nodes).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "consul_raft_rpc_appendEntries{quantile=\"0.99\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "consul_raft_rpc_appendEntries{quantile=\"0.5\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Leader Raft Commit Latency 99th and 50th (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "consul_raft_commitTime{quantile=\"0.99\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "consul_raft_commitTime{quantile=\"0.5\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Raft FSM Apply Latency per 5 minutes (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "rate(consul_raft_fsm_apply_sum[5m])\n/\nrate(consul_raft_fsm_apply_count[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Raft Apply Rate per 5 minutes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(consul_raft_apply[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Raft thread main saturation (percentage)",
     "type": "timeseries",
     "description": "An approximate measurement of the proportion of time the main Raft goroutine is busy and unavailable to accept new work.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "consul_raft_thread_main_saturation{pod=~\"consul-server-.*\",quantile=\"0.9\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Raft thread FSM saturation (percentage)",
     "type": "timeseries",
     "description": "An approximate measurement of the proportion of time the FSM Raft goroutine is busy and unavailable to accept new work.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "consul_raft_thread_fsm_saturation{pod=~\"consul-server-.*\", quantile=\"0.9\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Leadership Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average latency of leader reconcile per 5 minutes (ms)",
     "type": "timeseries",
     "description": "Measures the time spent updating the raft store from the serf member information.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "rate(consul_leader_reconcile_sum{pod=~\"consul-server-.*\"}[5m])\n/ \nrate(consul_leader_reconcile_count{pod=~\"consul-server-.*\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Count of a new leader elected [so far] (increasing only)",
     "type": "timeseries",
     "description": "Increments whenever a Consul server becomes a leader.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum(consul_raft_state_leader{pod=~\"consul-server-.*\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilization (Consul Servers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage in Seconds (Consul servers)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"consul\", pod=~\"consul-server-.*\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Limit in Seconds (Consul Servers)",
     "type": "gauge",
     "description": "All consul servers have the same limit",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{resource=\"cpu\", pod=\"consul-server-0\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage (Consul servers)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container=\"consul\", pod=~\"consul-server-.*\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Limit (Consul Servers)",
     "type": "gauge",
     "description": "All consul servers have the same limit",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=\"consul-server-0\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk usage",
     "type": "gauge",
     "description": "Gives the filesystem storage used by the container",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Read/Write total per 5 minutes (Consul servers)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"consul-server-.*\", container=\"consul\"}[5m])) by (pod, device)",
       "legendFormat": "writes, {pod=\"{{pod}}\", device=\"{{device}}\"}"
      },
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"consul-server-.*\", container=\"consul\"}[5m])) by (pod, device)",
       "legendFormat": "reads, {pod=\"{{pod}}\", device=\"{{device}}\"}"
      }
     ]
    },
    {
     "title": "Received bytes total per 5 minutes (Consul servers)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"consul-server-.*\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilization (Consul Clients) - N/A in agentless mode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage in Seconds (Consul Clients)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"consul\", pod=~\"consul-client-.*\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Limit in Seconds (Consul Clients)",
     "type": "gauge",
     "description": "All consul clients have the same limit",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"consul-client-.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage (Consul clients)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container=\"consul\", pod=~\"consul-client-.*\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Limit (Consul Clients)",
     "type": "gauge",
     "description": "All consul servers have the same limit",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"consul-client-.*\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilization (Connect Injector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage in Seconds (Connect Injector)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{pod=~\".*-connect-injector-.*\",container=\"sidecar-injector\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Limit in Seconds (Connect Injector)",
     "type": "gauge",
     "description": "All consul servers have the same limit",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\", container=\"sidecar-injector\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage (Connect Injector)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~\".*-connect-injector-.*\",container=\"sidecar-injector\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Limit (Connect Injector)",
     "type": "gauge",
     "description": "All consul servers have the same limit",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_limits{resource=\"memory\", container=\"sidecar-injector\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Feature: Catalog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Catalog Register Count per 5 minutes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(rate(consul_catalog_register_count{pod=~\"consul-server-.*\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average latency of catalog register per 5 minutes (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "rate(consul_catalog_register_sum{pod=~\"consul-server-.*\"}[5m])\n/\nrate(consul_catalog_register_count{pod=~\"consul-server-.*\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ACL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "ACL Token Resolve Count per 5 minutes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(rate(consul_acl_ResolveToken_count{pod=~\"consul-server-.*\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average latency of resolving ACL token per 5 minutes (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "rate(consul_acl_ResolveToken_sum{pod=~\"consul-server-.*\"}[5m])/rate(consul_acl_ResolveToken_count{pod=~\"consul-server-.*\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of ACL token cache hit per 5 minutes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "rate(consul_acl_token_cache_hit{pod=~\"consul-server-.*\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of ACL token cache miss per 5 minutes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "rate(consul_acl_token_cache_miss{pod=~\"consul-server-.*\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of RPC requests per 5 minutes - client side ",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent in client mode makes an RPC request to a Consul server",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "rate(consul_client_rpc{namespace=\"consul\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC Accept Connection Count Rate per 5 minutes - server side",
     "type": "timeseries",
     "description": "Increments when a server accepts an RPC connection.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "rate(consul_rpc_accept_conn{namespace=\"consul\",pod=~\"consul-server-.*\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Failed RPC requests per 5 minutes - client side ",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent in client mode makes an RPC request to a Consul server and fails.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "rate(consul_client_rpc_failed{namespace=\"consul\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of RPC requests per 5 minutes - server side",
     "type": "timeseries",
     "description": "Increments when a server receives a Consul-related RPC request.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "rate(consul_rpc_request{namespace=\"consul\",pod=~\"consul-server-.*\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Exceeded RPC requests per 5 minutes - client side ",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent in client mode makes an RPC request to a Consul server gets rate limited by that agent's limits configuration.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "rate(consul_client_rpc_exceeded{namespace=\"consul\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error rate of RPC requests per 5 minutes - server side",
     "type": "timeseries",
     "description": "Increments when a server returns an error from an RPC request.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "rate(consul_rpc_request_error{namespace=\"consul\",pod=~\"consul-server-.*\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}