// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: pbauth/v2beta1/computed_traffic_permissions.proto

package authv2beta1

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *ComputedTrafficPermissions) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *ComputedTrafficPermissions) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
