// Code generated by protoc-gen-resource-types. DO NOT EDIT.

package authv2beta1

import (
	"github.com/hashicorp/consul/proto-public/pbresource"
)

const (
	GroupName = "auth"
	Version   = "v2beta1"
)

/* ---------------------------------------------------------------------------
 * auth.v2beta1.ComputedTrafficPermissions
 *
 * This following section contains constants variables and utility methods
 * for interacting with this kind of resource.
 * -------------------------------------------------------------------------*/
const (
	ComputedTrafficPermissionsKind  = "ComputedTrafficPermissions"
	ComputedTrafficPermissionsScope = pbresource.Scope_SCOPE_NAMESPACE
)

var ComputedTrafficPermissionsType = &pbresource.Type{
	Group:        GroupName,
	GroupVersion: Version,
	Kind:         ComputedTrafficPermissionsKind,
}

func (_ *ComputedTrafficPermissions) GetResourceType() *pbresource.Type {
	return ComputedTrafficPermissionsType
}

func (_ *ComputedTrafficPermissions) GetResourceScope() pbresource.Scope {
	return ComputedTrafficPermissionsScope
}

/* ---------------------------------------------------------------------------
 * auth.v2beta1.NamespaceTrafficPermissions
 *
 * This following section contains constants variables and utility methods
 * for interacting with this kind of resource.
 * -------------------------------------------------------------------------*/
const (
	NamespaceTrafficPermissionsKind  = "NamespaceTrafficPermissions"
	NamespaceTrafficPermissionsScope = pbresource.Scope_SCOPE_NAMESPACE
)

var NamespaceTrafficPermissionsType = &pbresource.Type{
	Group:        GroupName,
	GroupVersion: Version,
	Kind:         NamespaceTrafficPermissionsKind,
}

func (_ *NamespaceTrafficPermissions) GetResourceType() *pbresource.Type {
	return NamespaceTrafficPermissionsType
}

func (_ *NamespaceTrafficPermissions) GetResourceScope() pbresource.Scope {
	return NamespaceTrafficPermissionsScope
}

/* ---------------------------------------------------------------------------
 * auth.v2beta1.PartitionTrafficPermissions
 *
 * This following section contains constants variables and utility methods
 * for interacting with this kind of resource.
 * -------------------------------------------------------------------------*/
const (
	PartitionTrafficPermissionsKind  = "PartitionTrafficPermissions"
	PartitionTrafficPermissionsScope = pbresource.Scope_SCOPE_PARTITION
)

var PartitionTrafficPermissionsType = &pbresource.Type{
	Group:        GroupName,
	GroupVersion: Version,
	Kind:         PartitionTrafficPermissionsKind,
}

func (_ *PartitionTrafficPermissions) GetResourceType() *pbresource.Type {
	return PartitionTrafficPermissionsType
}

func (_ *PartitionTrafficPermissions) GetResourceScope() pbresource.Scope {
	return PartitionTrafficPermissionsScope
}

/* ---------------------------------------------------------------------------
 * auth.v2beta1.TrafficPermissions
 *
 * This following section contains constants variables and utility methods
 * for interacting with this kind of resource.
 * -------------------------------------------------------------------------*/
const (
	TrafficPermissionsKind  = "TrafficPermissions"
	TrafficPermissionsScope = pbresource.Scope_SCOPE_NAMESPACE
)

var TrafficPermissionsType = &pbresource.Type{
	Group:        GroupName,
	GroupVersion: Version,
	Kind:         TrafficPermissionsKind,
}

func (_ *TrafficPermissions) GetResourceType() *pbresource.Type {
	return TrafficPermissionsType
}

func (_ *TrafficPermissions) GetResourceScope() pbresource.Scope {
	return TrafficPermissionsScope
}

/* ---------------------------------------------------------------------------
 * auth.v2beta1.WorkloadIdentity
 *
 * This following section contains constants variables and utility methods
 * for interacting with this kind of resource.
 * -------------------------------------------------------------------------*/
const (
	WorkloadIdentityKind  = "WorkloadIdentity"
	WorkloadIdentityScope = pbresource.Scope_SCOPE_NAMESPACE
)

var WorkloadIdentityType = &pbresource.Type{
	Group:        GroupName,
	GroupVersion: Version,
	Kind:         WorkloadIdentityKind,
}

func (_ *WorkloadIdentity) GetResourceType() *pbresource.Type {
	return WorkloadIdentityType
}

func (_ *WorkloadIdentity) GetResourceScope() pbresource.Scope {
	return WorkloadIdentityScope
}
