// Code generated by protoc-json-shim. DO NOT EDIT.
package pbproxystate

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for AccessLogs
func (this *AccessLogs) MarshalJSON() ([]byte, error) {
	str, err := AccessLogsMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AccessLogs
func (this *AccessLogs) UnmarshalJSON(b []byte) error {
	return AccessLogsUnmarshaler.Unmarshal(b, this)
}

var (
	AccessLogsMarshaler   = &protojson.MarshalOptions{}
	AccessLogsUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
