// Code generated by protoc-json-shim. DO NOT EDIT.
package pbproxystate

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for Endpoints
func (this *Endpoints) MarshalJSON() ([]byte, error) {
	str, err := EndpointsMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Endpoints
func (this *Endpoints) UnmarshalJSON(b []byte) error {
	return EndpointsUnmarshaler.Unmarshal(b, this)
}

// MarshalJSON is a custom marshaler for Endpoint
func (this *Endpoint) MarshalJSON() ([]byte, error) {
	str, err := EndpointsMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Endpoint
func (this *Endpoint) UnmarshalJSON(b []byte) error {
	return EndpointsUnmarshaler.Unmarshal(b, this)
}

var (
	EndpointsMarshaler   = &protojson.MarshalOptions{}
	EndpointsUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
