// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package tenancyv2beta1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Partition within kubernetes types, where deepcopy-gen is used.
func (in *Partition) DeepCopyInto(out *Partition) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Partition. Required by controller-gen.
func (in *Partition) DeepCopy() *Partition {
	if in == nil {
		return nil
	}
	out := new(Partition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Partition. Required by controller-gen.
func (in *Partition) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
