// Code generated by mockery v2.37.1. DO NOT EDIT.

package mockpbdns

import mock "github.com/stretchr/testify/mock"

// UnsafeDNSServiceServer is an autogenerated mock type for the UnsafeDNSServiceServer type
type UnsafeDNSServiceServer struct {
	mock.Mock
}

type UnsafeDNSServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeDNSServiceServer) EXPECT() *UnsafeDNSServiceServer_Expecter {
	return &UnsafeDNSServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedDNSServiceServer provides a mock function with given fields:
func (_m *UnsafeDNSServiceServer) mustEmbedUnimplementedDNSServiceServer() {
	_m.Called()
}

// UnsafeDNSServiceServer_mustEmbedUnimplementedDNSServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedDNSServiceServer'
type UnsafeDNSServiceServer_mustEmbedUnimplementedDNSServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedDNSServiceServer is a helper method to define mock.On call
func (_e *UnsafeDNSServiceServer_Expecter) mustEmbedUnimplementedDNSServiceServer() *UnsafeDNSServiceServer_mustEmbedUnimplementedDNSServiceServer_Call {
	return &UnsafeDNSServiceServer_mustEmbedUnimplementedDNSServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedDNSServiceServer")}
}

func (_c *UnsafeDNSServiceServer_mustEmbedUnimplementedDNSServiceServer_Call) Run(run func()) *UnsafeDNSServiceServer_mustEmbedUnimplementedDNSServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeDNSServiceServer_mustEmbedUnimplementedDNSServiceServer_Call) Return() *UnsafeDNSServiceServer_mustEmbedUnimplementedDNSServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeDNSServiceServer_mustEmbedUnimplementedDNSServiceServer_Call) RunAndReturn(run func()) *UnsafeDNSServiceServer_mustEmbedUnimplementedDNSServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnsafeDNSServiceServer creates a new instance of UnsafeDNSServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeDNSServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeDNSServiceServer {
	mock := &UnsafeDNSServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
