// Code generated by mockery v2.15.0. DO NOT EDIT.

package cache

import mock "github.com/stretchr/testify/mock"

// MockRequest is an autogenerated mock type for the Request type
type MockRequest struct {
	mock.Mock
}

// CacheInfo provides a mock function with given fields:
func (_m *MockRequest) CacheInfo() RequestInfo {
	ret := _m.Called()

	var r0 RequestInfo
	if rf, ok := ret.Get(0).(func() RequestInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(RequestInfo)
	}

	return r0
}

type mockConstructorTestingTNewMockRequest interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRequest creates a new instance of MockRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRequest(t mockConstructorTestingTNewMockRequest) *MockRequest {
	mock := &MockRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
