// export const GET = 'GET';
// export const HEAD = 'HEAD';
// export const POST = 'POST';
export const PUT = 'PUT';
export const DELETE = 'DELETE';
// export const CONNECT = 'CONNECT';
// export const OPTIONS = 'OPTIONS';
// export const TRACE = 'TRACE';
// export const PATCH = 'PATCH';
