all: false
dir: .
structname: '{{.InterfaceName}}'
pkgname: e2e
recursive: false
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/hashicorp/consul/internal/tools/protoc-gen-grpc-clone/e2e/proto:
    interfaces:
      Simple_FlowClient: {}
      SimpleClient: {}
