on:
  issues:
    types: [opened, closed, deleted, reopened]
  pull_request_target:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  workflow_dispatch:

name: Jira Sync

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Jira sync
    steps:    
      - name: Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Set ticket type
        id: set-ticket-type
        run: |
          if [[ "${{ contains(github.event.issue.labels.*.name, 'type/]bug') }}" == "true" ]]; then
            echo "::set-output name=type::Bug"
          elif [[ "${{ contains(github.event.issue.labels.*.name, 'type/enhancement') }}" == "true" ]]; then
            echo "::set-output name=type::Story"
          else
            echo "::set-output name=type::Task"
          fi
      - name: Set ticket labels
        if: github.event.action == 'opened'
        id: set-ticket-labels
        run: |
          LABELS="[consul]"
          echo "::set-output name=labels::${LABELS}"
          
      - name: Check if team member
        if: github.event.action == 'opened' && steps.set-ticket-type.outputs.type == 'Task'
        id: is-team-member
        run: |
          TEAM=consul
          ROLE="$(hub api orgs/hashicorp/teams/${TEAM}/memberships/${{ github.actor }} | jq -r '.role | select(.!=null)')"
          if [[ -n ${ROLE} ]]; then
            echo "Actor ${{ github.actor }} is a ${TEAM} team member"
            echo "::set-output name=message::true"
          else
            echo "Actor ${{ github.actor }} is NOT a ${TEAM} team member"
            echo "::set-output name=message::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.JIRA_SYNC_GITHUB_TOKEN }}

      - name: Create ticket
        if: ( github.event.action == 'opened' && steps.set-ticket-type.outputs.type != 'Task' ) || ( github.event.action == 'opened' && steps.set-ticket-type.outputs.type == 'Task' && steps.is-team-member.outputs.message == 'false' )
        uses: tomhjp/gh-action-jira-create@v0.1.3
        with:
          project: DIAG
          issuetype: "${{ steps.set-ticket-type.outputs.type }}"
          summary: "${{ github.event.repository.name }} [${{ steps.set-ticket-type.outputs.type }} #${{ github.event.issue.number || github.event.pull_request.number }}]: ${{ github.event.issue.title || github.event.pull_request.title }}"
          description: "${{ github.event.issue.body || github.event.pull_request.body }}\n\n_Created in GitHub by ${{ github.actor }}._"
          # customfield_10089 is "Issue Link", customfield_10371 is "Source" (use JIRA API to retrieve)
          extraFields: '{ "customfield_10089": "${{ github.event.issue.html_url || github.event.pull_request.html_url }}",
                          "customfield_10371": { "value": "GitHub" },            
                          "components": [{ "name": "${{ github.event.repository.name }}" }],
                          "labels": ${{ steps.set-ticket-labels.outputs.labels }} }'

      - name: Search
        if: github.event.action != 'opened'
        id: search
        uses: tomhjp/gh-action-jira-search@v0.2.1
        with:
          # cf[10089] is Issue Link (use JIRA API to retrieve)
          jql: 'issuetype = "${{ steps.set-ticket-type.outputs.type }}" and cf[10089] = "${{ github.event.issue.html_url || github.event.pull_request.html_url }}"'

      - name: Sync comment
        if: github.event.action == 'created' && steps.search.outputs.issue
        uses: tomhjp/gh-action-jira-comment@v0.1.0
        with:
          issue: ${{ steps.search.outputs.issue }}
          comment: "${{ github.actor }} ${{ github.event.review.state || 'commented' }}:\n\n${{ github.event.comment.body || github.event.review.body }}\n\n${{ github.event.comment.html_url || github.event.review.html_url }}"

      - name: Close ticket
        if: ( github.event.action == 'closed' || github.event.action == 'deleted' ) && steps.search.outputs.issue
        uses: atlassian/gajira-transition@v2.0.1
        with:
          issue: ${{ steps.search.outputs.issue }}
          transition: "Closed"

      - name: Reopen ticket
        if: github.event.action == 'reopened' && steps.search.outputs.issue
        uses: atlassian/gajira-transition@v2.0.1
        with:
          issue: ${{ steps.search.outputs.issue }}
          transition: "To Do"
