name: check-go-mod

on:
  workflow_call:
    inputs:
      runs-on:
        description: An expression indicating which kind of runners to use.
        required: true
        type: string
      repository-name:
        required: true
        type: string
      go-version:
        required: true
        type: string
    secrets:
      elevated-github-token:
        required: true
jobs:
  check-go-mod:
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    # NOTE: This step is specifically needed for ENT. It allows us to access the required private HashiCorp repos.
    - name: Setup Git
      if: ${{ endsWith(inputs.repository-name, '-enterprise') }}
      run: git config --global url."https://${{ secrets.elevated-github-token }}:@github.com".insteadOf "https://github.com"
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: ${{ inputs.go-version }}
    # Run on all go.mod (include submodules).
    - run: make go-mod-tidy
    - run: |
        if [[ -n $(git status -s) ]]; then
          echo "Git directory has changes"
          git status -s
          exit 1
        fi
