name: Notify Outcome (Slack)

on:
  push:
    branches:
      - vikram/*
  repository_dispatch:
    types:
      - notify-outcome
      - notify-outcome::*
  workflow_call:
    inputs:
      slack_channel:
        description: 'The Slack channel assigned to notify the outcome'
        required: true
        type: string

  workflow_dispatch: # <--- NEW: For manual testing
    inputs:
      slack_channel:
        description: 'Slack Channel (e.g., #my-test-channel)'
        required: true
        type: string
        default: 'C093M9T79QB'

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      # Determine inputs source (workflow_call vs. workflow_dispatch vs. repository_dispatch)
      # and normalize them into environment variables for easier access.
      - name: Set Notification Variables
        id: set_vars
        run: |
          # Prioritize workflow_call inputs, then workflow_dispatch inputs, then repository_dispatch client_payload
          # This makes it flexible for different triggers

          # Slack Channel
          if [ -n "${{ inputs.slack_channel }}" ]; then
            echo "SLACK_CHANNEL=${{ inputs.slack_channel }}" >> $GITHUB_ENV
          elif [ -n "${{ github.event.client_payload.payload.slack_channel }}" ]; then
            echo "SLACK_CHANNEL=${{ github.event.client_payload.payload.slack_channel }}" >> $GITHUB_ENV
          elif [ -n "${{ github.event.inputs.slack_channel }}" ]; then
            echo "SLACK_CHANNEL=${{ github.event.inputs.slack_channel }}" >> $GITHUB_ENV
          else
            echo "SLACK_CHANNEL=C093M9T79QB" >> $GITHUB_ENV
          fi

      - name: Send Slack Notification
        uses: archive/github-actions-slack@c643e5093620d65506466f2c9b317d5d29a5e517
        id: notify
        with:
          slack-webhook-url: ${{ secrets.CONSUL_PROTECTED_BRANCH_TEST_SLACK_WEBHOOK }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-text: |
            Hi vikram,
            The workflow has completed successfully.
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CONSUL_PROTECTED_BRANCH_TEST_SLACK_WEBHOOK }}