# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This action ensures that Envoy is up to date on main and release branches.
# This workflow is only triggered on the main and release branches and will
# only perform a version check when a new release branch is created
# Contact Consul team for any questions

name: Verify Envoy Version

on:
  push:
    branches:
      - main
      - release/**

jobs:
  verify-envoy-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # by default the checkout action doesn't checkout all branches
      - name: Run Envoy Version Verification for main and release branches
        run: ./.github/scripts/verify_envoy_version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}